# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 14:47
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutInfo', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': '\u0645\u0646 \u0646\u062d\u0646',
                'verbose_name_plural': '\u0645\u0646 \u0646\u062d\u0646',
            },
        ),
        migrations.CreateModel(
            name='ArtPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name': '\u0641\u0646',
                'verbose_name_plural': '\u0641\u0646',
            },
        ),
        migrations.CreateModel(
            name='CulturePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name': '\u062b\u0642\u0627\u0641\u0629',
                'verbose_name_plural': '\u062b\u0642\u0627\u0641\u0629',
            },
        ),
        migrations.CreateModel(
            name='MedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name': '\u0637\u0628',
                'verbose_name_plural': '\u0637\u0628',
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name': '\u0627\u062e\u0628\u0627\u0631',
                'verbose_name_plural': '\u0627\u062e\u0628\u0627\u0631',
            },
        ),
    ]
